[package]
name = "pontus-service"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
dotenvy = "0.15.7"
jsonwebtoken = "9.3.0"
rocket = {version = "0.5.1", features = ["json"]}
serde = "1.0.216"
serde_json = "1.0.133"
